### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Ferdinandum** [Autovot/SC_Spanish_SOK#16]
**Describe el fallo**
El nombre de los componentes no debe ser traducido:

Algún Ejemplo:
item_NameCOOL_AEGS_S01_Bracer_SCItem=Muñequera
item_NameCOOL_AEGS_S01_Glacier_SCItem=glaciar
item_NameCOOL_AEGS_S01_Polar=Polar
item_NameCOOL_AEGS_S01_Tundra=Tundra
item_NameCOOL_AEGS_S02_Arctic=artico
item_NameCOOL_AEGS_S02_Boreal=boreal

**Comment by zzettazz** [comment]
Buenas, muchas gracias, acaba de ser corregido

**Comment by Akaradrin** [comment]
"Bengalas" y "Distorsión" (Flares/ Noise) son palabras demasiado largas y rompen la interfaz en las naves que tienen varios sistemas antimisiles (como la Hércules). Tal vez poniendo BENG y DIST sería suficiente, aunque yo utilizaría un término distinto a "Distorsión" para que no haya confusión con las armas de distorsión.

Gracias por vuestro trabajo :)
![Sin título](https://github.com/Autovot/SC_Spanish_SOK/assets/107347979/7c2bc862-455c-4d3c-bfb7-7c0f880326cd)

**Comment by zzettazz** [comment]
Buenas @Akaradrin , podrías abrir un nuevo ISSUE si no es mucha molestia, por favor?

**Comment by Akaradrin** [comment]
ostras, perdona, no me di cuenta XD
