### ISSUE TITLE
Convenio traducciones del Modo Interacción

### ISSUE THREAD

**Issue by JimmyVaras** [Autovot/SC_Spanish_SOK#17]
Debido a que juego con esta traducción, estoy notando que algunas opciones del modo interacción (F) son bastante largas y me gustaría proponer simplificar las acciones, sobretodo las más comunes que usamos todos los días. Pongo algunos ejemplos del estado actual y la versión inglesa para apreciar que ellos tampoco usan una sintaxis perfecta, pero se entiende perfectamente. 

**ESPAÑOL ACTUAL**
```
ui_interactor_enter_pilot_seat=Subirse al asiento del piloto
ui_interactor_enter_gunner_seat=Subirse al asiento de artillero
ui_interactor_use_bed=Acostarse en la cama
```

**INGLÉS ACTUAL**
```
ui_interactor_enter_pilot_seat=Enter Pilot Seat
ui_interactor_enter_gunner_seat=Enter Gunner Seat
ui_interactor_use_bed=Enter Bed
```

**EJEMPLO PROPUESTA ESPAÑOL**
```
ui_interactor_enter_pilot_seat=Entrar asiento piloto
ui_interactor_enter_gunner_seat=Entrar asiento artillero
ui_interactor_use_bed=Entrar cama
```

Prefiero conocer vuestra opinión antes de tocar las correcciones. Gracias por el trabajo chicos.

**Comment by zzettazz** [comment]
Buenas, que te parecería?:

ui_interactor_enter_pilot_seat=Subirse asiento piloto
ui_interactor_enter_gunner_seat=Subirse asiento artillero
ui_interactor_use_bed=Acostarse

**Comment by JimmyVaras** [comment]
Yo lo veo bien, y si vosotros también, me lo apunto para darle un repaso al resto del estilo cuando pueda.

**Comment by zzettazz** [comment]
Perfecto, lo acabamos de corregir.
