### ISSUE TITLE
"Bengalas" y "Distorsión" rompen el HUD ocasionalmente

### ISSUE THREAD

**Issue by Akaradrin** [Autovot/SC_Spanish_SOK#18]
"Bengalas" y "Distorsión" (Flares/ Noise) son palabras demasiado largas y rompen la interfaz en las naves que tienen varios sistemas antimisiles (como la Hércules). Tal vez poniendo BENG y DIST sería suficiente, aunque yo utilizaría un término distinto a "Distorsión" para que no haya confusión con las armas de distorsión.

Gracias por vuestro trabajo :)
![Sin título](https://github.com/Autovot/SC_Spanish_SOK/assets/107347979/fd12a508-0c84-4589-a24a-3cd80cc2a18b)

**Comment by zzettazz** [comment]
Buenas, podríamos poner CHAFF y BENG, que opinas?

**Comment by Akaradrin** [comment]
Originalmente el "noise" se llamaba "chaff" y CIG lo cambió por algún motivo, pero creo que es un término válido que utiliza incluso la wikipedia en español (aunque sea un barbarismo). Se puede hacer la prueba dejando "BENGALA" y "CHAFF" a ver si no rompe el HUD, y si lo rompe todavía, usar BENG / BNGL y CHAFF.

**Comment by zzettazz** [comment]
Perfecto, lo dejamos como BNGL Y CHAFF
