### ISSUE TITLE
Algunas correcciones:

### ISSUE THREAD

**Issue by Akaradrin** [Autovot/SC_Spanish_SOK#19]
Buenaaas.

Algunas cositas más que me he encontrado:

- "Administrador de equipamiento de vehículos" (el título) se solapa con otro texto. Tal vez "Gestión de equipo de vehículos" sería más apropiado (o simplemente Administración/ Gestión de vehículos).
- La pestaña "SISTEMAS" aparece toda en mayúsculas, pero "Armas" y "Otros" aparecen en minúscula.
- En el listado de equipo, los Disipadores (coolers) aparecen como "Enfriador" pero luego como "tipo de artículo" (abajo a la derecha en la captura) aparecen como "Refrigerador".
- Algunos componentes (como el "eos" o el "termal") tienen el nombre en minúscula", otros aparecen traducidos (como "Rush" por "Correr") y otros sin traducir (como "QuickCool"). Lo de la minúscula deduzco que es una errata o descuido, pero para lo otro habría que escoger un criterio :) (se traducen los nombres de todos o ninguno). Por compatibilidad con ERKUL y otras webs, yo soy partidario de no traducirlos.
- Y un detalle mas, el "Quantum Drive" sería el "Impulsor Cuántico" más que "Impulsión Cuántica" y normalmente se habla de "escudos", en plural, con las naves espaciales, así que "Generador de Escudos" suena mejor que "Generador de Escudo", al menos a mi gusto, aunque vosotros decidís.

¡Muchas gracias por el currazo!
![Sin título](https://github.com/Autovot/SC_Spanish_SOK/assets/107347979/f15a516c-2234-437d-abe4-387c29f5db9e)

**Comment by zzettazz** [comment]
Buenas, todos los errores que acabas de comenta acaban de ser arreglados.  Te recomendamos actualizar la versión de la traducción a la v0.7.0-PRE, la cual será lanzada en un par de minutos.
Muchísimas gracias por reportarlo, nos ayudais muchísimo reportando los poblemas.
En cuanto publique la v0.7.0-PRE te adjunto el enlace y cierro el issue

**Comment by zzettazz** [comment]
Ya está publicada: https://github.com/Autovot/SC_Spanish_SOK/releases/tag/v0.7.0-pe
