### ISSUE TITLE
[BUG] Munición y cargador mal traducido

### ISSUE THREAD

**Issue by Thord82** [Autovot/SC_Spanish_SOK#21]
todos o la gran mayoría de los cargadores balísticos tanto el nombre como en la descripción están traducidos como Revista

**Pasos para reproducirlo**
Ejemplo:
1. Abrir pantalla de compra de armas
2. ver el nombre  y la descripción de los cargadores sobre todo los balisticos como el de la P4

revisando el archivo gobal.ini del proyecto hay 57 casos la mayoría de ellos creo que la palabra correcta sería cargador o en algunos casos podría ser munición según el contexto. 

Gracias por vuestro trabajo y esfuerzo!.

 (Ejemplo: 3.20 LIVE spanish_(spain))

**Comment by zzettazz** [comment]
Buenas @Thord82, muchas gracias por el reporte, acaba de ser corregido. Será implementado en una Release mañana

**Comment by zzettazz** [comment]
Buenas noticias @Thord82 , acabamos de sacar el release de la v0.7.0, ya lo puedes descargar y actualizar! 🎉
