### ISSUE TITLE
[BUG] errores de traducción y ortográficos

### ISSUE THREAD

**Issue by Thord82** [Autovot/SC_Spanish_SOK#23]
He estado revisando el archivo global.ini lineal a lineal y he encontrado algunos errores en la traducción, otros de contexto y ortográficos.
llevo tan solo las primeras 230 líneas revisadas pero creo que ya tengo una tanda para reportar.
PD: soy informático, y a modo amater he participado en proyectos de traducción de juegos (de mesa mayormente) pero si os puedo ayudar de una forma mas activa, podéis contar conmigo.

Errores de traducción
Línea 42 
ATC_PortOlisar=Servicios de desemnave en Port Olisar
Correcto: Servicios de aterrizaje…
Línea 70
Admin_Counter_Marker_01=Entrega de entrega
Correcto: me falta contexto o al menos la frase original, pero creo que hace referencia a:
Marcador de entrega. Pero si se trata del puesto de entrega de paquetes sería Puesto de entrega.
Línea 91
AmbassadorFlights_RepUI_Focus=Servicios de librea
Si se trata de descripción sería “Servicios de transporte”
Línea 62055
p_protectandresupply_wreck_021=Uniforme de barco de suministros
correcto: barco sería nave, pero desconozco la frase original para que tenga sentido.
Línea 106
BHG_Certification_Criminal_Title=Licencia de captura y detención de jugadores: ~mission(TargetName)
Creo que la licencia debería nombrarse como “Licencia de Cazarrecompensas de jugadores”

Línea 180
BarMenu_SubMenu_Liquor=Espiritu
La palabra correcta es: Licor
Línea 223
BitZeros_RepUI_Description=Se rumorea que un descarado colectivo de hackers fue iniciado por un grupo de adolescentes descontentos de microTech que se unieron por su afinidad por la tecnologia antigua. Aburridos por delincuentes mas serios, buscan emociones fuertes y buscan ganar algo de dinero, vivir a lo grande y dedicarse a las principales corporaciones de Stanton. Con una fuerte preferencia por la infiltracion y los subterfugios digitales, se sabe que recurren a ayuda externa cuando los trabajos requieren un enfoque mas directo.
La traducción correcta sería: 
BitZeros_RepUI_Description= Un descarado grupo(o colectivo) de hackers que, según se rumorea, fue fundado por un grupo de adolescentes descontentos de microTech que se unieron por su afinidad por la tecnologia antigua. Aburridos de los delitos más serios, buscan emociones fuertes y buscan ganar algo de dinero, vivir a lo grande y fastidiar a las grandes corporaciones de Stanton. Con una fuerte preferencia por la infiltracion y los subterfugios digitales, se sabe que recurren a ayuda externa cuando los trabajos requieren un enfoque más directo.
Errores menores de acentuación
Linea 49
Aciedo_RepUI_Description=Tras la conclusión de la Primera Guerra Tevarin, la humanidad estaba ansiosa por comenzar a explorar las estrellas nuevamente. Aciedo comenzó su vida como un fabricante de naves incipiente centrado en la creación de naves de exploración de largo alcance. Si bien tuvieron un éxito moderado con el diseño inicial de su nave, fueron los drones de comunicación incluidos los que se destacaron por su confiabilidad y éxito de transmisión. Los capitanes de todo el Imperio recién formado comenzaron a pedirle a Aciedo que les vendiera comandos directamente. Durante el primer año de ofrecerlos, las ventas se dispararon y no paso mucho tiempo antes de que Aciedo decidiera dejar de fabricar naves por completo. Hoy en día, son el mayor proveedor de servicios de comunicación de la UEE, manejan más del 70% de todas las comunicaciones y operan relés de comunicaciones, matrices de comunicación y drones de comunicación en todo el Imperio.
Línea 50
Aciedo_RepUI_Focus=Servicios de comunicación
Línea 58
Adagio_BasicSalvage_Desc_01=Atención:\n\nLos derechos a un nuevo Reclamo de Salvamento están disponibles para su compra. Se proporcionará acceso exclusivo a las coordenadas verificadas de la nave en el espacio monitoreado tras la confirmación de la transferencia de crédito. Las coordenadas permanecerán accesibles mientras el contrato aceptado este activo. Cuando esté satisfecho con la cantidad de material que ha recuperado, puede abandonar el contrato anticipadamente sin penalización para borrar las coordenadas de su mapa estelar.\n\nContrato #~mission(ClaimNumber):\n• Nave: ~mission(Ship) \n• Causa del accidente: ~mission(ShipStory)\n• Ubicacion: ~mission(location)\n\nAdagio Rights Division
Línea 61
Adagio_RepUI_Description=Fundada por personal de logistica naval retirado, Adagio tuvo exito apoyando el voraz apetito de recursos del complejo militar-industrial de la era Messer a traves de sus operaciones de chatarrería. Después del fin del régimen de Messer, Adagio, como muchos otros contratistas militares, perdió su contrato y la empresa se vio obligada a buscar nuevas fuentes de ingresos. En última instancia, esto llevo a Adagio a comenzar a revender los derechos de chatarrería que habían adquirido a capitanes independientes y otras empresas de diversos tamaños.
Línea 63
Adagio_RepUI_Focus=Chatarrería
Línea 68
Admin_Ask_Work=¿Tiene algún trabajo?
Línea 78
Admin_Small_Talk=¿Cómo estás?
La palabra “área” repetida numerosas veces hay que sustituirla por “área”
Línea 80
Advocacy_RepUI_Description,P=[PH] Descripción de la promoción
Línea 81
Advocacy_RepUI_Focus,P=[PH] Enfoque de promoción

Línea 83
Advocacy_RepUI_Headquarters,P=[PH] Sede de promoción

Línea 84
Advocacy_RepUI_Leadership,P=[PH] Liderazgo en promoción
Línea 86
Alerts_BeingArrested=Permanece donde estás, arresto en curso

La palabra “reputación” aparece numerosas veces, hay que sustituirla por “reputación”
Línea 90
AmbassadorFlights_RepUI_Description=Ambassador Flights se ha ganado la reputación de ser el servicio de transporte preferido de ejecutivos y personalidades VIP de todo el imperio. Si bien operan su propia flota de vehículos premium que contratan para transportar a su clientela adinerada, para ampliar aún más sus servicios también contratan pilotos privados que cumplen con sus altos estándares de higiene, comodidad y privacidad.
La palabra “seran” aparece numerosas ocasiones, hay que sustituirla por “serán”
Línea 101
ApprehendViolentInmate_MissionDescription,P=Durante su condena, un preso ha infringido las normas penitenciarias. Ha estado cometiendo delitos durante su condena y debe ser detenido. Los reclusos que estén dispuestos a intentar dar caza al mismo serán recompensados por detenerlo.
Línea 105
BHG_Certification_Criminal_Desc=Por recomendación de uno de nuestros miembros, el Gremio de Cazarrecompensas desea ofrecerle la oportunidad de obtener su Licencia de Detención de Sospechosos.\n\nEsto significaría que está cualificado para rastrear y detener a sospechosos buscados que han demostrado ser más esquivos que los objetivos típicos. A menudo tienen habilidades de pilotaje avanzadas, comportamientos difíciles de predecir y más recursos que el objetivo promedio, lo que los convierte en un verdadero desafío. \n\nPara completar con éxito este proceso de certificación, debe detener al sospechoso: ~mission(TargetName).\n\nNombre del sospechoso: ~mission(TargetName).
En este párrafo creo que el nombre de “licencia de Detención de Sospechosos” debería llamarse “Licencia de Cazarecompensas”

**Versión del juego y idioma**
3.20 LIVE spanish_(spain)

**Comment by zzettazz** [comment]
Buenas, esta tarde corregiremos los errores, gracias por reportarlo. En cuanto a lo que has comentado sobre participar de una forma mas activa, si controlas un poco, podrías hacer un Pull Request, con eso nos puedes pasar tu versión traducida para ser posteriormente revisada por nosotros y en caso de obtener el "visto bueno" haríamos un Merge (Fusionar tus correcciones con nuestra versión)

**Comment by Thord82** [comment]
de acuerdo. he creado mi rama y subido dos commit, que son dos bloque de traducción de dialogos contextualizados según  la situación, y creo haber creado correctamente el Pull Request, por si me puedes confirmar que así es.
gracias.

**Comment by zzettazz** [comment]
Buenas, a priori no parece que se haya creado el pull request

**Comment by Autovot** [comment]
> de acuerdo. he creado mi rama y subido dos commit, que son dos bloque de traducción de dialogos contextualizados según la situación, y creo haber creado correctamente el Pull Request, por si me puedes confirmar que así es. gracias.

Cuando estas en tu fork, debería salirte una barra, donde pone, contribute y sync, en contribute hay un botón para hacer una pull request al repo principal.
Importante, el main es solo para relases, actualmente se esta trabajando en la rama [`feat/v0.7.0`](https://github.com/Autovot/SC_Spanish_SOK/tree/feat/v0.7.0)
Ejemplo:
![image](https://github.com/Autovot/SC_Spanish_SOK/assets/87210193/643c6d28-b63a-4b52-994b-e6b467d5d5a7)
![image](https://github.com/Autovot/SC_Spanish_SOK/assets/87210193/798c6721-99bc-4003-b8fb-1a86d8b0f30a)

**Comment by zzettazz** [comment]
Los cambios de tu fork han sido aplicados en la versión v.0.8.0 🎉🎉

**Comment by Thord82** [comment]
vale ahora si debería aparecer la peticion del pull request de mi rama y debe estar hecha la petición sobre la feet/v0.8.0
