### ISSUE TITLE
Mejora en traducción

### ISSUE THREAD

**Issue by Dragris** [Autovot/SC_Spanish_SOK#27]
**Describe el fallo**
La traducción en la línea:
Inner_Thought_SpoolQD=Unidad cuantica de carrete
parece incorrecta, creo que algo como "Carga del motor cuántico" representaría mejor la acción que se lleva a cabo.

**Pasos para reproducirlo**
Ejemplo:
1. Mirar el botón para cargar el salto cuántico en alguna nave como la Gladius.

**Imágenes**
![image](https://github.com/Autovot/SC_Spanish_SOK/assets/17302041/e4b0a919-1050-4f66-8f0c-bd1b59bda0a1)

**Versión del juego y idioma**
3.20 LIVE spanish_(spain)

P.D.: ¿Existe alguna manera de crear directamente alguna pull request proponiendo cambios?

**Comment by zzettazz** [comment]
Buenas @Dragris puedes crear un fork para tí y luego un pull request comparando la última versión feat con tu fork

**Comment by Dragris** [comment]
¡Muchas gracias por la respuesta! Me haré un fork e intentaré ir colaborando
