### ISSUE TITLE
[ERROR/MEJORA TRADUCCION]

### ISSUE THREAD

**Issue by 0zzyt0** [Autovot/SC_Spanish_SOK#41]
Cambio de texto para cuadrarlo con los botones en Ascensores Ejemplo:

Actualmente porne: ASCENSOR EN CAMINO
Sustituir por: EN CAMINO...

Asi entra dentro.

Estoy jugando actualmente (Ejemplo: 3.21 LIVE spanish v0.9.2

**Comment by zzettazz** [comment]
Arreglado, gracias por tu contribución =) <3
