### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by ismaelviac** [Autovot/SC_Spanish_SOK#42]
**Describe el fallo**
Traduccion incorrecta
Cambiar 'archivos adjuntos' por 'complementos'

**Pasos para reproducirlo**
Ejemplo:
Ver complementos para armas en tienda de armaduras CRU L1 

**Imágenes**

![ScreenShot-2023-10-26_12-36-21-A19](https://github.com/Autovot/SC_Spanish_SOK/assets/59666577/7334e42c-3da3-48aa-96c9-311153be0cb3)

**Versión del juego y idioma**
 3.21 LIVE spanish_(spain)

**Comment by zzettazz** [comment]
Buenas, por favor, actualiza a la última versión. Por el momento no encontramos lo que nos has adjuntado, lo que significa que fué arreglado anteriormente. Te recomendamos que actualices a la última versión

**Comment by ismaelviac** [comment]
pit_weapon_attachments_drop_prompt_title=Advertencia de intercambio de archivos adjuntos
linea 62511

**Comment by zzettazz** [comment]
Esa linea es parte de una traducción, por lo que no se vería afectado
