### ISSUE TITLE
[BUG] extraccion de objetivo: Riley Aguayo (?RT)

### ISSUE THREAD

**Issue by Papoyjazz** [Autovot/SC_Spanish_SOK#58]
**Describe el fallo**
Una pequeña descripción del fallo

**Pasos para reproducirlo**
Ejemplo:
1. Abrir MobiGlass
2. ir a Mercenario
3. Misión extraccion de objetivo  Riley Aguayo (?RT)
4. no aparece el texto- (contractor bounty fps description)
![Captura de pantalla 2023-11-25 130133](https://github.com/Autovot/SC_Spanish_SOK/assets/45545042/6729dd58-fb3e-41dd-8f35-e591f784b438)

**Versión del juego y idioma**
Star Citizen Alpha 3.21.1 LIVE.8892745

**Comment by Autovot** [comment]
Linea reparada desde hace tiempo, se me olvido avisar, mia culpa, gracias por el aviso y siento el retraso de la contestación 
```ini
crusader_bounty_fps_tokenLink_Description=~mission(Contractor|BountyFPSDescription)
```
